export enum ErrorCode {
	// General errors
	INVALID_INPUT = 'INVALID_INPUT',
	NOT_FOUND = 'NOT_FOUND',
	UNAUTHORIZED = 'UNAUTHORIZED',
	FORBIDDEN = 'FORBIDDEN',
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
	UKNOWN_ERROR = 'UNKNOWN_ERROR',

	// User-related errors
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
	TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',

	// Product-related errors
	PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
	PRODUCT_OUT_OF_STOCK = 'PRODUCT_OUT_OF_STOCK',

	// Order-related errors
	ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
	ORDER_ALREADY_SHIPPED = 'ORDER_ALREADY_SHIPPED',

	// Payment-related errors
	PAYMENT_FAILED = 'PAYMENT_FAILED',

	// TypeORM errors codes
	UNIQUE_VIOLATION = '23505',
	FOREIGN_KEY_VIOLATION = '23503',
	NOT_NULL_VIOLATION = '23502',
	CHECK_VIOLATION = '23514',
	EXCLUSION_VIOLATION = '23P01',
}